apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-pvc
  namespace: confluence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ebs-gp3
