apiVersion: v1
kind: Service
metadata:
  name: confluence-service
  namespace: confluence
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: |
      Environment=Development,Owner=nunnikrishnan@altimetrik.com,Project=Development,Application=Chatbot
spec:
  selector:
    app: confluence
  ports:
    - port: 31000
      targetPort: 8090
  type: LoadBalancer
